#!/bin/bash
pip install --upgrade pip
pip install bs4
pip install lxml
pip install simplejson
pip install mlflow
pip install airflow
pip install tushare
pip install -r requirements.txt

jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.34.0
jupyter labextension install jupyter-leaflet
